language: sh

env:
  global:
    - BUILD_DIR="build"
    - CMAKE_CONFIGURATION="release"

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        snaps:
          - name: cmake
            confinement: classic
            channel: latest/candidate
            
before_install:
  # Install gcc-9 and g++-9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt-get install gcc-9 g++-9

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin"; fi
  - mkdir $BUILD_DIR
  - cd $BUILD_DIR
  - cmake ..

script:
  - cmake --build $BUILD_DIR --target space
  - cmake --build $BUILD_DIR --target Tests_run