language: sh

env:
  global:
    - BUILD_DIR="build"
    - CMAKE_CONFIGURATION="release"

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
          - g++-9
          - cmake

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin"; fi
  - mkdir $BUILD_DIR
  - cd $BUILD_DIR
  - cmake ..

script:
  - cmake --build $BUILD_DIR --target space
  - cmake --build $BUILD_DIR --target Tests_run